// <auto-generated />
namespace Project_63135350.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addMessOrderCTM : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addMessOrderCTM));
        
        string IMigrationMetadata.Id
        {
            get { return "202410151415086_addMessOrderCTM"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
